package co.com.edu.udea.micine.model;
// Generated 11/02/2015 05:36:49 PM by Hibernate Tools 3.6.0



/**
 * ComboHasFactura generated by hbm2java
 */
public class ComboHasFactura  implements java.io.Serializable {


     private ComboHasFacturaId id;
     private Factura factura;
     private Combo combo;
     private int numeroCombos;

    public ComboHasFactura() {
    }

    public ComboHasFactura(ComboHasFacturaId id, Factura factura, Combo combo, int numeroCombos) {
       this.id = id;
       this.factura = factura;
       this.combo = combo;
       this.numeroCombos = numeroCombos;
    }
   
    public ComboHasFacturaId getId() {
        return this.id;
    }
    
    public void setId(ComboHasFacturaId id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Combo getCombo() {
        return this.combo;
    }
    
    public void setCombo(Combo combo) {
        this.combo = combo;
    }
    public int getNumeroCombos() {
        return this.numeroCombos;
    }
    
    public void setNumeroCombos(int numeroCombos) {
        this.numeroCombos = numeroCombos;
    }




}


