package co.com.edu.udea.micine.model;
// Generated 11/02/2015 05:36:49 PM by Hibernate Tools 3.6.0



/**
 * ComboHasFacturaId generated by hbm2java
 */
public class ComboHasFacturaId  implements java.io.Serializable {


     private int comboIdcombo;
     private int facturaIdFactura;

    public ComboHasFacturaId() {
    }

    public ComboHasFacturaId(int comboIdcombo, int facturaIdFactura) {
       this.comboIdcombo = comboIdcombo;
       this.facturaIdFactura = facturaIdFactura;
    }
   
    public int getComboIdcombo() {
        return this.comboIdcombo;
    }
    
    public void setComboIdcombo(int comboIdcombo) {
        this.comboIdcombo = comboIdcombo;
    }
    public int getFacturaIdFactura() {
        return this.facturaIdFactura;
    }
    
    public void setFacturaIdFactura(int facturaIdFactura) {
        this.facturaIdFactura = facturaIdFactura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComboHasFacturaId) ) return false;
		 ComboHasFacturaId castOther = ( ComboHasFacturaId ) other; 
         
		 return (this.getComboIdcombo()==castOther.getComboIdcombo())
 && (this.getFacturaIdFactura()==castOther.getFacturaIdFactura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getComboIdcombo();
         result = 37 * result + this.getFacturaIdFactura();
         return result;
   }   


}


