package co.com.edu.udea.micine.model;
// Generated 11/02/2015 05:36:49 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * FuncionId generated by hbm2java
 */
public class FuncionId  implements java.io.Serializable {


     private int peliculaIdPelicula;
     private Date fecha;

    public FuncionId() {
    }

    public FuncionId(int peliculaIdPelicula, Date fecha) {
       this.peliculaIdPelicula = peliculaIdPelicula;
       this.fecha = fecha;
    }
   
    public int getPeliculaIdPelicula() {
        return this.peliculaIdPelicula;
    }
    
    public void setPeliculaIdPelicula(int peliculaIdPelicula) {
        this.peliculaIdPelicula = peliculaIdPelicula;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FuncionId) ) return false;
		 FuncionId castOther = ( FuncionId ) other; 
         
		 return (this.getPeliculaIdPelicula()==castOther.getPeliculaIdPelicula())
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }

    @Override
    public String toString() {
        return "FuncionId{" + "peliculaIdPelicula=" + peliculaIdPelicula + ", fecha=" + fecha + '}';
    }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPeliculaIdPelicula();
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


