package co.com.edu.udea.micine.model;
// Generated 11/02/2015 05:36:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Funcion generated by hbm2java
 */
public class Funcion  implements java.io.Serializable {


     private FuncionId id;
     private Pelicula pelicula;
     private Tarifa tarifa;
     private Sala sala;
     private String estado;
     private Set<Boleta> boletas = new HashSet<Boleta>(0);

    public Funcion() {
    }

	
    public Funcion(FuncionId id, Pelicula pelicula, Tarifa tarifa, Sala sala, String estado) {
        this.id = id;
        this.pelicula = pelicula;
        this.tarifa = tarifa;
        this.sala = sala;
        this.estado = estado;
    }
    public Funcion(FuncionId id, Pelicula pelicula, Tarifa tarifa, Sala sala, String estado, Set<Boleta> boletas) {
       this.id = id;
       this.pelicula = pelicula;
       this.tarifa = tarifa;
       this.sala = sala;
       this.estado = estado;
       this.boletas = boletas;
    }
   
    public FuncionId getId() {
        return this.id;
    }
    
    public void setId(FuncionId id) {
        this.id = id;
    }
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }
    public Tarifa getTarifa() {
        return this.tarifa;
    }
    
    public void setTarifa(Tarifa tarifa) {
        this.tarifa = tarifa;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Boleta> getBoletas() {
        return this.boletas;
    }
    
    public void setBoletas(Set<Boleta> boletas) {
        this.boletas = boletas;
    }




}


