package co.com.edu.udea.micine.model;
// Generated 11/02/2015 05:36:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private SalaId id;
     private Cine cine;
     private Integer numeroAsientos;
     private Set<Funcion> funcions = new HashSet<Funcion>(0);
     private Set<Asiento> asientos = new HashSet<Asiento>(0);

    public Sala() {
    }

	
    public Sala(SalaId id, Cine cine) {
        this.id = id;
        this.cine = cine;
    }
    public Sala(SalaId id, Cine cine, Integer numeroAsientos, Set<Funcion> funcions, Set<Asiento> asientos) {
       this.id = id;
       this.cine = cine;
       this.numeroAsientos = numeroAsientos;
       this.funcions = funcions;
       this.asientos = asientos;
    }
   
    public SalaId getId() {
        return this.id;
    }
    
    public void setId(SalaId id) {
        this.id = id;
    }
    public Cine getCine() {
        return this.cine;
    }
    
    public void setCine(Cine cine) {
        this.cine = cine;
    }
    public Integer getNumeroAsientos() {
        return this.numeroAsientos;
    }
    
    public void setNumeroAsientos(Integer numeroAsientos) {
        this.numeroAsientos = numeroAsientos;
    }
    public Set<Funcion> getFuncions() {
        return this.funcions;
    }
    
    public void setFuncions(Set<Funcion> funcions) {
        this.funcions = funcions;
    }
    public Set<Asiento> getAsientos() {
        return this.asientos;
    }
    
    public void setAsientos(Set<Asiento> asientos) {
        this.asientos = asientos;
    }




}


