package co.com.edu.udea.micine.model;
// Generated 11/02/2015 05:36:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipooperador generated by hbm2java
 */
public class Tipooperador  implements java.io.Serializable {


     private Integer idTipoOperador;
     private String nombre;
     private Set<Operador> operadors = new HashSet<Operador>(0);

    public Tipooperador() {
    }

	
    public Tipooperador(String nombre) {
        this.nombre = nombre;
    }
    public Tipooperador(String nombre, Set<Operador> operadors) {
       this.nombre = nombre;
       this.operadors = operadors;
    }
   
    public Integer getIdTipoOperador() {
        return this.idTipoOperador;
    }
    
    public void setIdTipoOperador(Integer idTipoOperador) {
        this.idTipoOperador = idTipoOperador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Operador> getOperadors() {
        return this.operadors;
    }
    
    public void setOperadors(Set<Operador> operadors) {
        this.operadors = operadors;
    }




}


