package co.com.edu.udea.micine.model;
// Generated 11/02/2015 05:36:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopago generated by hbm2java
 */
public class Tipopago  implements java.io.Serializable {


     private Integer idTipoPago;
     private String nombreTipo;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Tipopago() {
    }

	
    public Tipopago(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public Tipopago(String nombreTipo, Set<Factura> facturas) {
       this.nombreTipo = nombreTipo;
       this.facturas = facturas;
    }
   
    public Integer getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(Integer idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


