package co.com.edu.udea.micine.model;
// Generated 11/02/2015 01:29:45 PM by Hibernate Tools 3.6.0



/**
 * AsientoId generated by hbm2java
 */
public class AsientoId  implements java.io.Serializable {


     private int idAsiento;
     private int localidadIdLocalidad;
     private int salaIdSala;
     private int salaCineIdCine;

    public AsientoId() {
    }

    public AsientoId(int idAsiento, int localidadIdLocalidad, int salaIdSala, int salaCineIdCine) {
       this.idAsiento = idAsiento;
       this.localidadIdLocalidad = localidadIdLocalidad;
       this.salaIdSala = salaIdSala;
       this.salaCineIdCine = salaCineIdCine;
    }
   
    public int getIdAsiento() {
        return this.idAsiento;
    }
    
    public void setIdAsiento(int idAsiento) {
        this.idAsiento = idAsiento;
    }
    public int getLocalidadIdLocalidad() {
        return this.localidadIdLocalidad;
    }
    
    public void setLocalidadIdLocalidad(int localidadIdLocalidad) {
        this.localidadIdLocalidad = localidadIdLocalidad;
    }
    public int getSalaIdSala() {
        return this.salaIdSala;
    }
    
    public void setSalaIdSala(int salaIdSala) {
        this.salaIdSala = salaIdSala;
    }
    public int getSalaCineIdCine() {
        return this.salaCineIdCine;
    }
    
    public void setSalaCineIdCine(int salaCineIdCine) {
        this.salaCineIdCine = salaCineIdCine;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsientoId) ) return false;
		 AsientoId castOther = ( AsientoId ) other; 
         
		 return (this.getIdAsiento()==castOther.getIdAsiento())
 && (this.getLocalidadIdLocalidad()==castOther.getLocalidadIdLocalidad())
 && (this.getSalaIdSala()==castOther.getSalaIdSala())
 && (this.getSalaCineIdCine()==castOther.getSalaCineIdCine());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAsiento();
         result = 37 * result + this.getLocalidadIdLocalidad();
         result = 37 * result + this.getSalaIdSala();
         result = 37 * result + this.getSalaCineIdCine();
         return result;
   }   


}


