package co.com.edu.udea.micine.model;
// Generated 11/02/2015 01:29:45 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Asiento generated by hbm2java
 */
public class Asiento  implements java.io.Serializable {


     private AsientoId id;
     private Localidad localidad;
     private Sala sala;
     private String estado;
     private Set<Boleta> boletas = new HashSet<Boleta>(0);

    public Asiento() {
    }

	
    public Asiento(AsientoId id, Localidad localidad, Sala sala) {
        this.id = id;
        this.localidad = localidad;
        this.sala = sala;
    }
    public Asiento(AsientoId id, Localidad localidad, Sala sala, String estado, Set<Boleta> boletas) {
       this.id = id;
       this.localidad = localidad;
       this.sala = sala;
       this.estado = estado;
       this.boletas = boletas;
    }
   
    public AsientoId getId() {
        return this.id;
    }
    
    public void setId(AsientoId id) {
        this.id = id;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Boleta> getBoletas() {
        return this.boletas;
    }
    
    public void setBoletas(Set<Boleta> boletas) {
        this.boletas = boletas;
    }




}


