package co.com.edu.udea.micine.model;
// Generated 11/02/2015 01:29:45 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cine generated by hbm2java
 */
public class Cine  implements java.io.Serializable {


     private Integer idCine;
     private String nombre;
     private String telefono;
     private String ciudad;
     private Set<Sala> salas = new HashSet<Sala>(0);
     private Set<Operador> operadors = new HashSet<Operador>(0);

    public Cine() {
    }

    public Cine(String nombre, String telefono, String ciudad, Set<Sala> salas, Set<Operador> operadors) {
       this.nombre = nombre;
       this.telefono = telefono;
       this.ciudad = ciudad;
       this.salas = salas;
       this.operadors = operadors;
    }
   
    public Integer getIdCine() {
        return this.idCine;
    }
    
    public void setIdCine(Integer idCine) {
        this.idCine = idCine;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set<Sala> getSalas() {
        return this.salas;
    }
    
    public void setSalas(Set<Sala> salas) {
        this.salas = salas;
    }
    public Set<Operador> getOperadors() {
        return this.operadors;
    }
    
    public void setOperadors(Set<Operador> operadors) {
        this.operadors = operadors;
    }




}


