package co.com.edu.udea.micine.model;
// Generated 11/02/2015 05:36:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Formato generated by hbm2java
 */
public class Formato  implements java.io.Serializable {


     private Integer idFormato;
     private String nombre;
     private Set<Pelicula> peliculas = new HashSet<Pelicula>(0);
     private Set<Tarifa> tarifas = new HashSet<Tarifa>(0);

    public Formato() {
    }

    public Formato(String nombre, Set<Pelicula> peliculas, Set<Tarifa> tarifas) {
       this.nombre = nombre;
       this.peliculas = peliculas;
       this.tarifas = tarifas;
    }
   
    public Integer getIdFormato() {
        return this.idFormato;
    }
    
    public void setIdFormato(Integer idFormato) {
        this.idFormato = idFormato;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Pelicula> getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set<Pelicula> peliculas) {
        this.peliculas = peliculas;
    }
    public Set<Tarifa> getTarifas() {
        return this.tarifas;
    }
    
    public void setTarifas(Set<Tarifa> tarifas) {
        this.tarifas = tarifas;
    }




}


