package co.com.edu.udea.micine.model;
// Generated 11/02/2015 05:36:49 PM by Hibernate Tools 3.6.0



/**
 * ReservaId generated by hbm2java
 */
public class ReservaId  implements java.io.Serializable {


     private int socioIdSocio;
     private int facturaIdFactura;

    public ReservaId() {
    }

    public ReservaId(int socioIdSocio, int facturaIdFactura) {
       this.socioIdSocio = socioIdSocio;
       this.facturaIdFactura = facturaIdFactura;
    }
   
    public int getSocioIdSocio() {
        return this.socioIdSocio;
    }
    
    public void setSocioIdSocio(int socioIdSocio) {
        this.socioIdSocio = socioIdSocio;
    }
    public int getFacturaIdFactura() {
        return this.facturaIdFactura;
    }
    
    public void setFacturaIdFactura(int facturaIdFactura) {
        this.facturaIdFactura = facturaIdFactura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservaId) ) return false;
		 ReservaId castOther = ( ReservaId ) other; 
         
		 return (this.getSocioIdSocio()==castOther.getSocioIdSocio())
 && (this.getFacturaIdFactura()==castOther.getFacturaIdFactura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSocioIdSocio();
         result = 37 * result + this.getFacturaIdFactura();
         return result;
   }   


}


