package co.com.edu.udea.micine.model;
// Generated 11/02/2015 01:29:45 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio  implements java.io.Serializable {


     private int idSocio;
     private String nombre;
     private String direccion;
     private String telefono;
     private boolean estado;
     private String cedula;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Tarjeta> tarjetas = new HashSet<Tarjeta>(0);

    public Socio() {
    }

	
    public Socio(int idSocio, String nombre, String telefono, boolean estado, String cedula) {
        this.idSocio = idSocio;
        this.nombre = nombre;
        this.telefono = telefono;
        this.estado = estado;
        this.cedula = cedula;
    }
    public Socio(int idSocio, String nombre, String direccion, String telefono, boolean estado, String cedula, Set<Factura> facturas, Set<Tarjeta> tarjetas) {
       this.idSocio = idSocio;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.estado = estado;
       this.cedula = cedula;
       this.facturas = facturas;
       this.tarjetas = tarjetas;
    }
   
    public int getIdSocio() {
        return this.idSocio;
    }
    
    public void setIdSocio(int idSocio) {
        this.idSocio = idSocio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<Tarjeta> getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Set<Tarjeta> tarjetas) {
        this.tarjetas = tarjetas;
    }




}


