package co.com.edu.udea.micine.model;
// Generated 11/02/2015 07:39:26 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private Integer idTarjeta;
     private Socio socio;
     private Integer puntos;
     private Date fechaCreacion;

    public Tarjeta() {
    }

	
    public Tarjeta(Socio socio, Date fechaCreacion) {
        this.socio = socio;
        this.fechaCreacion = fechaCreacion;
    }
    public Tarjeta(Socio socio, Integer puntos, Date fechaCreacion) {
       this.socio = socio;
       this.puntos = puntos;
       this.fechaCreacion = fechaCreacion;
    }
   
    public Integer getIdTarjeta() {
        return this.idTarjeta;
    }
    
    public void setIdTarjeta(Integer idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public Socio getSocio() {
        return this.socio;
    }
    
    public void setSocio(Socio socio) {
        this.socio = socio;
    }
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


