package co.com.edu.udea.micine.model;
// Generated 11/02/2015 07:39:26 AM by Hibernate Tools 3.6.0



/**
 * Tipooperador generated by hbm2java
 */
public class Tipooperador  implements java.io.Serializable {


     private Integer idTipoOperador;
     private Operador operador;
     private String nombre;

    public Tipooperador() {
    }

	
    public Tipooperador(String nombre) {
        this.nombre = nombre;
    }
    public Tipooperador(Operador operador, String nombre) {
       this.operador = operador;
       this.nombre = nombre;
    }
   
    public Integer getIdTipoOperador() {
        return this.idTipoOperador;
    }
    
    public void setIdTipoOperador(Integer idTipoOperador) {
        this.idTipoOperador = idTipoOperador;
    }
    public Operador getOperador() {
        return this.operador;
    }
    
    public void setOperador(Operador operador) {
        this.operador = operador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


